#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BotaNaRoda.Android.Resource", IsApplication=true)]

namespace BotaNaRoda.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_delete = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_gps = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_map = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_mode_edit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_refresh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_save = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int actionDelete = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int actionNew = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int actionRefresh = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int actionSave = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int itemAddressText = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int itemDescriptionText = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int itemsAuthor = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int itemsDescription = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int itemsDetailAuthor = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int itemsDetailDescription = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int itemsDetailImage = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int itemsDistance = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int itemsImageView = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int itemsListView = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int locationImageButton = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int mapImageButton = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int relativeLayout1 = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemEdit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Items = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemsListItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ItemEditMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ItemsMenu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
