#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BotaNaRoda.Android.Resource", IsApplication=true)]

namespace BotaNaRoda.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_delete = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_gps = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_map = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_mode_edit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_photo_camera = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_refresh = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_save = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int actionDelete = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int actionLocation = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int actionMap = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int actionNew = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int actionRefresh = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int actionSave = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int itemAddressText = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int itemDescriptionText = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int itemImageView = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int itemsAuthor = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int itemsDescription = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int itemsDetailAuthor = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int itemsDetailDescription = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int itemsDetailImage = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int itemsDistance = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int itemsImageView = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int itemsListView = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int locationImageButton = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int mapImageButton = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int relativeLayout1 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemEdit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Items = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemsListItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int ItemEditMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ItemsMenu = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
